[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_rs_test_example = "AQGaUitJF6dcuM4izL7QKTCfaNDsEFwFx2JoHYDQwd6p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/0xasimraza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
