[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sample = "6Kbnkku6Wq5AA2kZzdGujvYzEwBKrXFbtodVed5N5upD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
